### ISSUE TITLE
PYTHON-2470 Mongo-orchestration cannot start a 3.6 sharded cluster with PyMongo 3.6.0

### ISSUE THREAD

**Issue by ShaneHarvey** [10gen/mongo-orchestration#235]
PyMongo 3.6.0 adds implicit session ids and gossips cluster time. One of those is triggering this error when MO attempts to start a 3.6 sharded cluster.  

```
2017-12-05 23:29:32,557 [ERROR] mongo_orchestration.apps:68 - <function sh_create at 0x2aebaa0>
Traceback (most recent call last):
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/apps/__init__.py", line 66, in wrap
    return f(*arg, **kwd)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/apps/sharded_clusters.py", line 68, in sh_create
    result = _sh_create(data)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/apps/sharded_clusters.py", line 44, in _sh_create
    cluster_id = ShardedClusters().create(params)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/sharded_clusters.py", line 465, in create
    cluster = ShardedCluster(params)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/sharded_clusters.py", line 182, in __init__
    restart_with_auth(self.configdb_singleton._storage[config_id])
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/sharded_clusters.py", line 179, in restart_with_auth
    server_or_rs.restart(config_callback=add_auth)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/replica_sets.py", line 599, in restart
    server.restart(timeout, config_callback)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/servers.py", line 401, in restart
    return self.start(timeout)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/servers.py", line 345, in start
    self.run_command('isMaster')
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/servers.py", line 268, in run_command
    result = getattr(self.connection.admin, mode)(command, name, **d)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/servers.py", line 198, in connection
    connected(c)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/mongo_orchestration/common.py", line 133, in connected
    client.admin.command('ismaster')
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pymongo/database.py", line 532, in command
    codec_options, session=session, **kwargs)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pymongo/database.py", line 439, in _command
    client=self.__client)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pymongo/pool.py", line 496, in command
    collation=collation)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/data/mci/ab597b45cecf99b6c22088e6620b267c/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pymongo/helpers.py", line 146, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1512516572, 1) } with id: 0
```

**Comment by ajdavis** [comment]
This "Cache Reader No keys found for HMAC that is valid" error rings a bell, I think I've seen it before. It may be caused by a transient state that the replica set passes through during initialization. Do you know any more than I do?

**Comment by ajdavis** [comment]
Check with Jason Carey or Samantha Ritter. Searching Jira for "No keys found for HMAC that is valid" turns up dozens of related tickets and build failures, perhaps SERVER-31916 describes the root cause but I don't understand it.

**Comment by behackett** [comment]
Seems like some kind of timing issue. The entire cluster doesn't yet know the cluster time because parts of it aren't yet initialized?

**Comment by ShaneHarvey** [comment]
I believe [SERVER-31916](https://jira.mongodb.org/browse/SERVER-31916) is the cause and it's exacerbated by [PYTHON-1434](https://jira.mongodb.org/browse/PYTHON-1434).

**Comment by ShaneHarvey** [comment]
This is the situation mongo-orc  is in when it hits the error: 

1. mongo-orc starts the config server without auth.
1. mongo-orc adds the admin user.
1. mongo-orc kills the config server.
1. mongo-orc kills the config server with auth.
1. mongo-orc creates a MongoClient and attempts to run 'isMaster'.
1. MongoClient reads the following invalid $clusterTime from the config server: 
   ```
    {'clusterTime': Timestamp(1512682165, 1), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}
   ```
1. Because of [PYTHON-1434](https://jira.mongodb.org/browse/PYTHON-1434), the MongoClient never updates its maximum $clusterTime and all commands fail with the same error:
    ```
    Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1512682165, 1) } with id: 0
    ```

After [PYTHON-1434](https://jira.mongodb.org/browse/PYTHON-1434) is fixed, mongo-orc can retry the failed isMaster command. The retry will succeed once a valid $clusterTime is returned.

**Comment by ShaneHarvey** [comment]
This will be fixed by https://jira.mongodb.org/browse/SERVER-33585

However we should not upgrade to PyMongo 3.6 until mongo-orchestration can drop support for MongoDB 2.4

**Comment by ShaneHarvey** [comment]
Update: AFAIK we can drop support for MongoDB 2.4. No actively maintained driver still supports or tests MongoDB 2.4

We should now test whether we can finally upgrade to a modern version of pymongo. We may need to specify the `--enableMajorityReadConcern=false` command line option for MMAPv1 clusters a lone `KeyNotFound` error on 4.0 ([SERVER-52955](https://jira.mongodb.org/browse/SERVER-52955)).
