### ISSUE TITLE
SSL failures on Windows with MongoDB-latest (v3.7.3-340-g942d7f63c0)

### ISSUE THREAD

**Issue by ShaneHarvey** [10gen/mongo-orchestration#241]
Mongo-orchestration log:
```
2018-04-04 21:55:38,767 [ERROR] mongo_orchestration.servers:348 - isMaster command failed:
Traceback (most recent call last):
  File "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\servers.py", line 345, in start
    self.run_command('isMaster')
  File "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\servers.py", line 268, in run_command
    result = getattr(self.connection.admin, mode)(command, name, **d)
  File "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\servers.py", line 198, in connection
    connected(c)
  File "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\venv\lib\site-packages\mongo_orchestration\common.py", line 136, in connected
    client.admin.command('ismaster')
  File "c:\python27\lib\site-packages\pymongo\database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "c:\python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\python27\lib\site-packages\pymongo\mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "c:\python27\Lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\python27\lib\site-packages\pymongo\mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "c:\python27\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "c:\python27\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 10054] An existing connection was forcibly closed by the remote host
```

Mongod log:
```
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] MongoDB starting : pid=2652 port=27017 dbpath=c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\db\mongo-t8d0zo 64-bit host=WIN-OG64G79RBPA
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] db version v3.7.3-340-g942d7f63c0
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] git version: 942d7f63c009f82e334017a7d2a358b1b55e2a94
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] modules: enterprise 
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] build environment:
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten]     distmod: windows-64
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-04-04T21:52:35.949+0000 I CONTROL  [initandlisten] options: { config: "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\db\mongo-skpfkr", net: { bindIp: "127.0.0.1,::1", compression: { compressors: "zlib,snappy,noop" }, ipv6: true, port: 27017, ssl: { CAFile: "C:/data/mci/b650327e6a282b1f3a6847f2a2c477be/drivers-tools/.evergreen/x509gen/ca.pem", PEMKeyFile: "C:/data/mci/b650327e6a282b1f3a6847f2a2c477be/drivers-tools/.evergreen/x509gen/server.pem", mode: "requireSSL", weakCertificateValidation: true } }, replication: { enableMajorityReadConcern: true, oplogSizeMB: 100 }, setParameter: { enableTestCommands: "1" }, storage: { dbPath: "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\db\mongo-t8d0zo", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: "c:\data\mci\b650327e6a282b1f3a6847f2a2c477be\drivers-tools\.evergreen\orchestration\db\mongo-t8d0zo\mongod.log" } }
2018-04-04T21:52:35.951+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3327M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-04-04T21:52:35.982+0000 I STORAGE  [initandlisten] WiredTiger message [1522878755:982066][2652:2001351552], txn-recover: Set global recovery timestamp: 0
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] 
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.7.3-340-g942d7f63c0) of MongoDB.
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] **       Not recommended for production.
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] 
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] 
2018-04-04T21:52:36.005+0000 I CONTROL  [initandlisten] 
2018-04-04T21:52:36.006+0000 I CONTROL  [initandlisten] ** WARNING: The file system cache of this machine is configured to be greater than 40% of the total memory. This can lead to increased memory pressure and poor performance.
2018-04-04T21:52:36.006+0000 I CONTROL  [initandlisten] See http://dochub.mongodb.org/core/wt-windows-system-file-cache
2018-04-04T21:52:36.006+0000 I CONTROL  [initandlisten] 
2018-04-04T21:52:36.007+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 0485108f-4b83-409d-9026-ac4726ccfc44
2018-04-04T21:52:36.019+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
2018-04-04T21:52:36.023+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 95e0da61-84b4-42b1-99f0-e709900f020a
2018-04-04T21:52:37.281+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'c:/data/mci/b650327e6a282b1f3a6847f2a2c477be/drivers-tools/.evergreen/orchestration/db/mongo-t8d0zo/diagnostic.data'
2018-04-04T21:52:37.283+0000 I NETWORK  [initandlisten] waiting for connections on port 27017 ssl
2018-04-04T21:52:37.352+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:49269 #1 (1 connection now open)
2018-04-04T21:52:37.353+0000 I NETWORK  [conn1] end connection 127.0.0.1:49269 (0 connections now open)
2018-04-04T21:52:37.808+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:49270 #2 (1 connection now open)
2018-04-04T21:52:38.009+0000 E NETWORK  [conn2] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.009+0000 E NETWORK  [conn2] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.009+0000 I NETWORK  [conn2] Error receiving request from client: SSLHandshakeFailed: SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.. Ending connection from 127.0.0.1:49270 (connection id: 2)
2018-04-04T21:52:38.009+0000 I NETWORK  [conn2] end connection 127.0.0.1:49270 (0 connections now open)
2018-04-04T21:52:38.510+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:49272 #3 (1 connection now open)
2018-04-04T21:52:38.538+0000 E NETWORK  [conn3] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.538+0000 E NETWORK  [conn3] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.538+0000 I NETWORK  [conn3] Error receiving request from client: SSLHandshakeFailed: SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.. Ending connection from 127.0.0.1:49272 (connection id: 3)
```

It looks like something has changed in the server on Windows which makes the existing certificates invalid:
```
2018-04-04T21:52:38.538+0000 E NETWORK  [conn3] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.538+0000 E NETWORK  [conn3] SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.
2018-04-04T21:52:38.538+0000 I NETWORK  [conn3] Error receiving request from client: SSLHandshakeFailed: SSL peer certificate validation failed: (800B0110)The certificate is not valid for the requested usage.. Ending connection from 127.0.0.1:49272 (connection id: 3)
```

**Comment by behackett** [comment]
I bet this is related to native TLS on the server (i.e. secure channel support). @spencerjackson, any ideas?

**Comment by ShaneHarvey** [comment]
This started happening on March 30 with following server version:
```
db version v3.7.3-289-gf1bb8e1389
git version: f1bb8e1389d6aa458e5100f3eb753b80b1a4e4e7
allocator: tcmalloc
modules: enterprise 
build environment:
    distmod: windows-64
    distarch: x86_64
    target_arch: x86_64
```

**Comment by behackett** [comment]
My guess is this is related to https://jira.mongodb.org/browse/SERVER-33832
