### ISSUE TITLE
Cannot start sharded cluster with MongoDB 4.1.7 and 4.0.5

### ISSUE THREAD

**Issue by ShaneHarvey** [10gen/mongo-orchestration#261]
When starting a sharded cluster with MongoDB 4.1.7 or 4.0.5, adding the first shard fails with the following error from mongos:
```
RuntimeError: Error sending POST to cluster: Traceback (most recent call last):
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/apps/__init__.py", line 66, in wrap
    return f(*arg, **kwd)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/apps/sharded_clusters.py", line 68, in sh_create
    result = _sh_create(data)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/apps/sharded_clusters.py", line 44, in _sh_create
    cluster_id = ShardedClusters().create(params)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/sharded_clusters.py", line 477, in create
    cluster = ShardedCluster(params)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/sharded_clusters.py", line 90, in __init__
    info = self.member_add(cfg.get('id', None), shard_params)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/sharded_clusters.py", line 352, in member_add
    result = self._add(cfgs, member_id)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/sharded_clusters.py", line 329, in _add
    return self.router_command("addShard", (shard_uri, {"name": name}), is_eval=False)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/mongo_orchestration/sharded_clusters.py", line 318, in router_command
    result = getattr(self.connection().admin, mode)(command, name, **d)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/pymongo/database.py", line 516, in command
    codec_options, **kwargs)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/pymongo/database.py", line 428, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/shane/tmp/venv/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Could not find host matching read preference { mode: "primary" } for set 3f77e17f-81a0-4c51-b816-aab4fa008471
```

However, directly before this error MO runs `replSetGetStatus` and logs the response. The primary appears to be up and healthy:

> 2019-01-23 10:44:23,031 [DEBUG] mongo_orchestration.replica_sets:279 - command result: {'set': 'fa898a02-5635-4916-8bb4-4fcc3fcfa840', 'date': datetime.datetime(2019, 1, 23, 18, 44, 23, 31000), 'myState': 1, 'term': 1, 'syncingTo': '', 'syncSourceHost': '', 'syncSourceId': -1, 'heartbeatIntervalMillis': 2000, 'optimes': {'lastCommittedOpTime': {'ts': Timestamp(1548269062, 2), 't': 1}, 'readConcernMajorityOpTime': {'ts': Timestamp(1548269062, 2), 't': 1}, 'appliedOpTime': {'ts': Timestamp(1548269062, 2), 't': 1}, 'durableOpTime': {'ts': Timestamp(1548269062, 2), 't': 1}}, 'lastStableRecoveryTimestamp': Timestamp(1548269062, 1), 'lastStableCheckpointTimestamp': Timestamp(1548269062, 1), 'members': [{'_id': 0, 'name': 'localhost:27019', 'health': 1.0, 'state': 1, 'stateStr': 'PRIMARY', 'uptime': 5, 'optime': {'ts': Timestamp(1548269062, 2), 't': 1}, 'optimeDate': datetime.datetime(2019, 1, 23, 18, 44, 22), 'syncingTo': '', 'syncSourceHost': '', 'syncSourceId': -1, 'infoMessage': 'could not find member to sync from', 'electionTime': Timestamp(1548269060, 2), 'electionDate': datetime.datetime(2019, 1, 23, 18, 44, 20), 'configVersion': 1, 'self': True, 'lastHeartbeatMessage': ''}], 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1548269062, 2), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1548269062, 2)}

**Comment by ShaneHarvey** [comment]
Here's the mongos log:
```
2019-01-23T11:03:39.449-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:53774 #11 (2 connections now open)
2019-01-23T11:03:39.450-0800 I NETWORK  [conn11] received client metadata from 127.0.0.1:53774 conn11: { driver: { name: "PyMongo", version: "3.5.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.13.6" }, platform: "CPython 3.6.6.final.0" }
2019-01-23T11:03:59.530-0800 I COMMAND  [conn11] query admin.b36ed099-859e-44a0-8592-1d5be0052944/localhost:27019 command: { addShard: "b36ed099-859e-44a0-8592-1d5be0052944/localhost:27019", name: "demo-set-0", $db: "admin" } numYields:0 reslen:354 20079ms
2019-01-23T11:03:59.534-0800 I NETWORK  [conn11] end connection 127.0.0.1:53774 (1 connection now open)
2019-01-23T11:03:59.534-0800 I NETWORK  [conn10] end connection 127.0.0.1:53773 (0 connections now open)
2019-01-23T11:04:01.351-0800 I NETWORK  [ShardRegistry] Marking host localhost:1026 as failed :: caused by :: NotMaster: not master
2019-01-23T11:04:01.352-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:01.855-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:02.359-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:02.858-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:03.359-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:03.702-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:03.861-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:04.363-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:04.865-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:05.369-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:05.872-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:06.375-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:06.878-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:07.379-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:07.879-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:08.380-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:08.880-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:09.384-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:09.886-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:10.397-0800 W NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set d511e0dd-7e69-4bd0-b068-b724a59c164a
2019-01-23T11:04:10.397-0800 I NETWORK  [ReplicaSetMonitor-TaskExecutor] Cannot reach any nodes for set d511e0dd-7e69-4bd0-b068-b724a59c164a. Please check network connectivity and the status of the set. This has happened for 1 checks in a row.
```

And here's the config server's log (`localhost:1026` set `d511e0dd-7e69-4bd0-b068-b724a59c164a`):
```
2019-01-23T11:04:01.351-0800 D -        [conn24] User Assertion: NotMaster: not master src/mongo/db/service_entry_point_common.cpp 653
2019-01-23T11:04:01.351-0800 D COMMAND  [conn24] assertion while executing command 'findAndModify' on database 'config' with arguments '{ findAndModify: "lockpings", query: { _id: "Shanes-MacBook-Pro-2.local:27017:1548270211:8267092334528784163" }, update: { $set: { ping: new Date(1548270241350) } }, upsert: true, writeConcern: { w: "majority", wtimeout: 15000 }, maxTimeMS: 30000, $replData: 1, $clusterTime: { clusterTime: Timestamp(1548270237, 1), signature: { hash: BinData(0, 56232B3A6E30CE476C83384BD8A2ECAC301EAA12), keyId: 6649769917321052187 } }, $configServerState: { opTime: { ts: Timestamp(1548270237, 1), t: 1 } }, $db: "config" }': NotMaster: not master
2019-01-23T11:04:01.351-0800 I COMMAND  [conn24] command config.$cmd command: findAndModify { findAndModify: "lockpings", query: { _id: "Shanes-MacBook-Pro-2.local:27017:1548270211:8267092334528784163" }, update: { $set: { ping: new Date(1548270241350) } }, upsert: true, writeConcern: { w: "majority", wtimeout: 15000 }, maxTimeMS: 30000, $replData: 1, $clusterTime: { clusterTime: Timestamp(1548270237, 1), signature: { hash: BinData(0, 56232B3A6E30CE476C83384BD8A2ECAC301EAA12), keyId: 6649769917321052187 } }, $configServerState: { opTime: { ts: Timestamp(1548270237, 1), t: 1 } }, $db: "config" } numYields:0 ok:0 errMsg:"not master" errName:NotMaster errCode:10107 reslen:535 locks:{} protocol:op_msg 0ms
```

**Comment by ShaneHarvey** [comment]
Okay I figured this out. The problem is that my cluster config set `bind_ip` to "127.0.0.1" and also set the `ipv6` flag. The config server is unable to connect to the mongod because the server does not try both IPv4 and IPv6 on outgoing connections (https://jira.mongodb.org/browse/SERVER-33883). 

Setting `bind_ip` to "localhost" or "127.0.0.1,::1" avoids this issue.
