### ISSUE TITLE
Upgrade to CherryPy >= 9

### ISSUE THREAD

**Issue by ShaneHarvey** [10gen/mongo-orchestration#291]
We currently pin to CherryPy>=3.5.0,<9.0.0. CherryPy 8.9.1 is over 5 years old: https://pypi.org/project/CherryPy/8.9.1/

We should resolve whatever issue stopped us from using 9 (a bottle incompatibility I think?) and upgrade to a modern version.

**Comment by eramongodb** [comment]
This is currently blocking use of mongo-orchestration with Python 3.11 which [removed the `getargspec` function](https://docs.python.org/3/whatsnew/3.11.html#removed) (deprecated since 3.0):
```
Traceback (most recent call last):
  File "/data/mci/32b016b1eff3f6b672d0c260b8dbeeb7/mongoc/venv/lib/python3.11/site-packages/mongo_orchestration/server.py", line 132, in run
    run(get_app(), host=self.args.bind, port=self.args.port,
  File "/data/mci/32b016b1eff3f6b672d0c260b8dbeeb7/mongoc/venv/bin/bottle.py", line 3172, in run
    server.run(app)
  File "/data/mci/32b016b1eff3f6b672d0c260b8dbeeb7/mongoc/venv/bin/bottle.py", line 2807, in run
    from cherrypy import wsgiserver # This will fail for CherryPy >= 9
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/mci/32b016b1eff3f6b672d0c260b8dbeeb7/mongoc/venv/lib/python3.11/site-packages/cherrypy/__init__.py", line 71, in <module>
    from cherrypy import _cpdispatch as dispatch  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/mci/32b016b1eff3f6b672d0c260b8dbeeb7/mongoc/venv/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 214, in <module>
    getargspec = inspect.getargspec
                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```

[This comment](https://github.com/cherrypy/cherrypy/issues/1585#issuecomment-299404955) suggests a possible workaround for the import error observed with `CherryPy >= 9`:

```python
try:
    from cheroot import wsgi as wgsiserver
except ImportError:
    from cherrypy import wsgiserver
```

**Comment by eramongodb** [comment]
This may also require [bottle>=0.12.23](https://github.com/bottlepy/bottle/issues/1387#issuecomment-1203970665).
